version: '3.8'

services:
  web:
    build: .
    ports:
      - "10000:10000"
    environment:
      - UNSTRUCTURED_API_URL=${UNSTRUCTURED_API_URL:-https://api.unstructuredapp.io/general/v0/general}
      - UNSTRUCTURED_API_KEY=${UNSTRUCTURED_API_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped 