[project]
name = "lumos"
version = "0.0.2"
authors = [
    { name = "Arun Patro", email = "arun@lumiralabs.com" },
]
description = "A package for AI interactions"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.5",
    "litellm>=1.53.1",
    "pydantic>=2.10.2",
    "python-magic>=0.4.27",
    "structlog>=24.4.0",
    "uvicorn>=0.32.1",
]

[tool.uv]
dev-dependencies = [
    "ipykernel>=6.29.5",
    "pre-commit>=4.0.1",
    "pytest>=8.3.3",
]
